
# language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t nuenook/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nuenook/react-test npm run test

after_success:
    - docker build -t nuenook/multi-client ./client
    - docker build -t nuenook/multi-nginx ./nginx
    - docker build -t nuenook/multi-server ./server
    - docker build -t nuenook/multi-worker ./worker
    # Login in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to dodkcer hub
    - docker push nuenook/multi-client
    - docker push nuenook/multi-nginx
    - docker push nuenook/multi-server
    - docker push nuenook/multi-worker
