
# language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t nuenook/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nuenook/react-test npm run test

after_success:
    - docker build -t nuenook/multi-client ./client
    - docker build -t nuenook/multi-nginx ./nginx
    - docker build -t nuenook/multi-server ./server
    - docker build -t nuenook/multi-worker ./worker
    # Login in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to dodkcer hub
    - docker push nuenook/multi-client
    - docker push nuenook/multi-nginx
    - docker push nuenook/multi-server
    - docker push nuenook/multi-worker



deploy:
    provider: elasticbeanstalk
    edge: true
    region: "ap-southeast-1"
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-323601448954
    bucket_path: docker-multi
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master

    # deploy:
    #     # edge: true
    #     provider: elasticbeanstalk
    #     region: "ap-southeast-1"
    #     app: "docker-react"
    #     env: "DockerReact-env"
    #     bucket_name: "elasticbeanstalk-ap-southeast-1-323601448954"
    #     bucket_path: "docker-react"
    #     access_key_id: $AWS_ACCESS_KEY
    #     secret_access_key: $AWS_SECRET_KEY
    #     on:
    #         branch: master
